import type { StatusWord } from "./companies";

export type MandRow = {
  ticker: string;
  name: string;
  sector: string;
  s: number | null;
  status: StatusWord;
  lezing: string;
};

/** Desk-sourced rosters. S is copied from the attached mand HTML — never recomputed. */
export const MAND_ROSTERS: Record<string, MandRow[]> = {
  europa: [
    {
      ticker: "DSY",
      name: "Dassault Systèmes",
      sector: "Software",
      s: 80.5,
      status: "VOORLOPIG",
      lezing: "Dassault Systèmes (DSY) — europa. Hergebruik Top100-score. S=80,5 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit sterk, veerkracht solide (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "ATCO.A",
      name: "Atlas Copco",
      sector: "Industrieel/automatisering",
      s: 76.5,
      status: "VOORLOPIG",
      lezing: "Atlas Copco (ATCO.A) — europa. Hergebruik Top100-score. S=76,5 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit sterk, veerkracht solide (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "NVO",
      name: "Novo Nordisk",
      sector: "Semis/equipment",
      s: 74.8,
      status: "VOORLOPIG",
      lezing: "Novo Nordisk (NVO) — denmark. S=74,8 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit sterk, veerkracht de knip (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "SAP",
      name: "SAP",
      sector: "Software",
      s: 74.7,
      status: "VOORLOPIG",
      lezing: "SAP (SAP) — germany. S=74,7 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit sterk, veerkracht de knip (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "RELX",
      name: "RELX",
      sector: "Software",
      s: 74.3,
      status: "VOORLOPIG",
      lezing: "RELX (RELX) — uk. S=74,3 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit sterk, veerkracht de knip (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "NVS",
      name: "Novartis",
      sector: "Semis/equipment",
      s: 72.9,
      status: "VOORLOPIG",
      lezing: "Novartis (NVS) — switzerland. S=72,9 (VOORLOPIG, SEC/bedrijfsvoering-proxies): utiliteit sterk, veerkracht de knip (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "SAND",
      name: "Sandvik",
      sector: "Industrieel/automatisering",
      s: 71.9,
      status: "VOORLOPIG",
      lezing: "Sandvik (SAND) — europa. Hergebruik Top100-score. S=71,9 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit sterk, veerkracht de knip (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "ARM",
      name: "Arm",
      sector: "Semis/equipment",
      s: 71.6,
      status: "VOORLOPIG",
      lezing: "Arm (ARM) — europa. Hergebruik Top100-score. S=71,6 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit sterk, veerkracht solide (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "ABBNY",
      name: "ABB",
      sector: "Industrieel/automatisering",
      s: 70.9,
      status: "VOORLOPIG",
      lezing: "ABB (ABBNY) — switzerland. S=70,9 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit gemiddeld, veerkracht solide (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "ASML",
      name: "ASML",
      sector: "Semis/equipment",
      s: 70.7,
      status: "VOORLOPIG",
      lezing: "ASML (ASML) — europa. Hergebruik Top100-score. S=70,7 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit sterk, veerkracht solide (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "AZN",
      name: "AstraZeneca",
      sector: "Semis/equipment",
      s: 70.7,
      status: "VOORLOPIG",
      lezing: "AstraZeneca (AZN) — uk. S=70,7 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit sterk, veerkracht de knip (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "HEXA.B",
      name: "Hexagon",
      sector: "Software",
      s: 70.3,
      status: "VOORLOPIG",
      lezing: "Hexagon (HEXA.B) — europa. Hergebruik Top100-score. S=70,3 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit sterk, veerkracht de knip (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "ASM",
      name: "ASM International",
      sector: "Semis/equipment",
      s: 70.0,
      status: "VOORLOPIG",
      lezing: "ASM International (ASM) — europa. Hergebruik Top100-score. S=70,0 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit sterk, veerkracht solide (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "NXPI",
      name: "NXP Semiconductors",
      sector: "Semis/equipment",
      s: 69.8,
      status: "VOORLOPIG",
      lezing: "NXP Semiconductors (NXPI) — netherlands. S=69,8 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit sterk, veerkracht de knip (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "STM",
      name: "STMicroelectronics",
      sector: "Semis/equipment",
      s: 69.6,
      status: "VOORLOPIG",
      lezing: "STMicroelectronics (STM) — switzerland/france/italy. S=69,6 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit sterk, veerkracht solide (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "NOK",
      name: "Nokia",
      sector: "Telecom/media",
      s: 68.2,
      status: "VOORLOPIG",
      lezing: "Nokia (NOK) — finland. S=68,2 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit sterk, veerkracht solide (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "PHG",
      name: "Philips",
      sector: "Medtech/health",
      s: 66.8,
      status: "VOORLOPIG",
      lezing: "Philips (PHG) — netherlands. S=66,8 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit sterk, veerkracht de knip (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "ETN",
      name: "Eaton",
      sector: "Industrieel/automatisering",
      s: 65.2,
      status: "VOORLOPIG",
      lezing: "Eaton (ETN) — ireland. S=65,2 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit sterk, veerkracht de knip (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "SIE",
      name: "Siemens",
      sector: "Industrieel/automatisering",
      s: 64.3,
      status: "VOORLOPIG",
      lezing: "Siemens (SIE) — europa. Hergebruik Top100-score. S=64,3 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit sterk, veerkracht de knip (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "ERIC",
      name: "Ericsson",
      sector: "Telecom/media",
      s: 58.0,
      status: "VOORLOPIG",
      lezing: "Ericsson (ERIC) — sweden. S=58,0 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit gemiddeld, veerkracht de knip (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "KNEBV",
      name: "Kone",
      sector: "Industrieel/automatisering",
      s: null,
      status: "INCOMPLEET",
      lezing: "Kone (KNEBV, finland) staat in de Europa-sleeve, maar S is INCOMPLEET: Essay-naam; geen SEC primary companyfacts — INCOMPLEET. Geen verzonnen ratio’s. Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "SGE",
      name: "Sage Group",
      sector: "Software",
      s: null,
      status: "INCOMPLEET",
      lezing: "Sage Group (SGE, uk) staat in de Europa-sleeve, maar S is INCOMPLEET: Essay-naam; LSE/OTC zonder bruikbare SEC XBRL — INCOMPLEET. Geen verzonnen ratio’s. Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "WKL",
      name: "Wolters Kluwer",
      sector: "Software",
      s: null,
      status: "INCOMPLEET",
      lezing: "Wolters Kluwer (WKL, netherlands) staat in de Europa-sleeve, maar S is INCOMPLEET: Essay-naam; WTKWY OTC — SEC companyfacts 404 — INCOMPLEET. Geen verzonnen ratio’s. Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "IFNNY",
      name: "Infineon",
      sector: "Semis/equipment",
      s: null,
      status: "INCOMPLEET",
      lezing: "Infineon (IFNNY, germany) staat in de Europa-sleeve, maar S is INCOMPLEET: OTC ADR — SEC companyfacts 404. Geen verzonnen ratio’s. Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "SPXSF",
      name: "Spirax-Sarco",
      sector: "Industrieel/automatisering",
      s: null,
      status: "INCOMPLEET",
      lezing: "Spirax-Sarco (SPXSF, uk) staat in de Europa-sleeve, maar S is INCOMPLEET: OTC ADR — SEC companyfacts 404. Geen verzonnen ratio’s. Aparte lijst — niet automatisch W37-universum.",
    },
  ],
  mijnbouw: [
    {
      ticker: "FNV",
      name: "Franco-Nevada",
      sector: "streaming/royalty",
      s: 84.4,
      status: "VOORLOPIG",
      lezing: "Franco-Nevada (metal): streaming/royalty — contractueel metaal. S=84,4 hergebruik mining/WORLD. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "WPM",
      name: "Wheaton Precious Metals",
      sector: "streaming/royalty",
      s: 84.2,
      status: "VOORLOPIG",
      lezing: "Wheaton Precious Metals (metal): streaming/royalty — contractueel metaal. S=84,2 hergebruik mining/WORLD. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "B",
      name: "Barrick Mining",
      sector: "goud",
      s: 72.2,
      status: "VOORLOPIG",
      lezing: "Barrick Mining (miner): goudproductie (eigen mijnen). S=72,2 hergebruik mining/WORLD. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "SAND",
      name: "Sandvik",
      sector: "equipment",
      s: 71.9,
      status: "VOORLOPIG",
      lezing: "Sandvik (equip): mijnbouw-/zwaar materieel (equip). S=71,9 hergebruik mining/WORLD. Status VOORLOPIG.",
    },
    {
      ticker: "NEM",
      name: "Newmont",
      sector: "goud",
      s: 71.5,
      status: "VOORLOPIG",
      lezing: "Newmont (miner): goudproductie (eigen mijnen, post-Newcrest). S=71,5 hergebruik mining/WORLD. Status VOORLOPIG. Dossier B3 Semaform aanwezig.",
    },
    {
      ticker: "BHP",
      name: "BHP Group",
      sector: "diversified",
      s: 70.5,
      status: "VOORLOPIG",
      lezing: "BHP Group (miner): diversified mining (ijzererts, koper, kolen). S=70,5 hergebruik mining/WORLD. Status VOORLOPIG. Dossier B3 Semaform aanwezig.",
    },
    {
      ticker: "RIO",
      name: "Rio Tinto",
      sector: "diversified",
      s: 70.2,
      status: "VOORLOPIG",
      lezing: "Rio Tinto (miner): Pilbara-ijzererts + aluminium/koper. S=70,2 hergebruik mining/WORLD. Status VOORLOPIG. Dossier B3 Semaform aanwezig.",
    },
    {
      ticker: "AEM",
      name: "Agnico Eagle",
      sector: "goud",
      s: 69.8,
      status: "VOORLOPIG",
      lezing: "Agnico Eagle (miner): goudmijnen (Canada/Australia/Mexico/Finland). S=69,8 hergebruik mining/WORLD. Status VOORLOPIG. Dossier B3 Semaform aanwezig.",
    },
    {
      ticker: "SCCO",
      name: "Southern Copper",
      sector: "koper",
      s: 69.5,
      status: "VOORLOPIG",
      lezing: "Southern Copper (miner): koperproductie (LatAm). S=69,5 hergebruik mining/WORLD. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "PAAS",
      name: "Pan American Silver",
      sector: "goud/zilver",
      s: 68.7,
      status: "VOORLOPIG",
      lezing: "Pan American Silver (miner): zilver/goudproductie. S=68,7 hergebruik mining/WORLD. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "KGC",
      name: "Kinross Gold",
      sector: "goud",
      s: 68.3,
      status: "VOORLOPIG",
      lezing: "Kinross Gold (miner): goudproductie. S=68,3 hergebruik mining/WORLD. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "SQM",
      name: "SQM",
      sector: "lithium/RE",
      s: 68.1,
      status: "VOORLOPIG",
      lezing: "SQM (metal): lithium / specialty chemicals. S=68,1 hergebruik mining/WORLD. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "CAT",
      name: "Caterpillar",
      sector: "equipment",
      s: 67.3,
      status: "VOORLOPIG",
      lezing: "Caterpillar (equip): zwaar materieel (OEM, mining-adjacent). S=67,3 hergebruik mining/WORLD. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "HBM",
      name: "Hudbay Minerals",
      sector: "koper",
      s: 61.5,
      status: "VOORLOPIG",
      lezing: "Hudbay Minerals (miner): koper/zink/goud miner. S=61,5 hergebruik mining/WORLD. Status VOORLOPIG.",
    },
    {
      ticker: "VALE",
      name: "Vale",
      sector: "diversified",
      s: 58.7,
      status: "VOORLOPIG",
      lezing: "Vale (miner): ijzererts / diversified miner. S=58,7 hergebruik mining/WORLD. Status VOORLOPIG.",
    },
    {
      ticker: "FCX",
      name: "Freeport-McMoRan",
      sector: "koper",
      s: 58.0,
      status: "VOORLOPIG",
      lezing: "Freeport-McMoRan (miner): koper/goud miner. S=58,0 hergebruik mining/WORLD. Status VOORLOPIG.",
    },
    {
      ticker: "ALB",
      name: "Albemarle",
      sector: "lithium/RE",
      s: 55.7,
      status: "VOORLOPIG",
      lezing: "Albemarle (metal): lithium / specialty chemicals. S=55,7 hergebruik mining/WORLD. Status VOORLOPIG.",
    },
    {
      ticker: "TECK",
      name: "Teck Resources",
      sector: "diversified",
      s: 55.2,
      status: "VOORLOPIG",
      lezing: "Teck Resources (miner): koper/zink/kolen miner. S=55,2 hergebruik mining/WORLD. Status VOORLOPIG.",
    },
    {
      ticker: "MP",
      name: "MP Materials",
      sector: "lithium/RE",
      s: 49.5,
      status: "VOORLOPIG",
      lezing: "MP Materials (metal): rare earths / magnetics. S=49,5 hergebruik mining/WORLD. Status VOORLOPIG.",
    },
    {
      ticker: "AAL.L",
      name: "Anglo American",
      sector: "diversified",
      s: null,
      status: "INCOMPLEET",
      lezing: "Geen SEC primary companyfacts scorebaar zonder te verzinnen — INCOMPLEET (mining-run).",
    },
    {
      ticker: "FM.TO",
      name: "First Quantum",
      sector: "koper",
      s: null,
      status: "INCOMPLEET",
      lezing: "Geen SEC primary companyfacts scorebaar zonder te verzinnen — INCOMPLEET (mining-run).",
    },
    {
      ticker: "GLEN",
      name: "Glencore",
      sector: "diversified",
      s: null,
      status: "INCOMPLEET",
      lezing: "Geen SEC primary companyfacts scorebaar zonder te verzinnen — INCOMPLEET (mining-run).",
    },
  ],
  software: [
    {
      ticker: "ZS",
      name: "Zscaler",
      sector: "security_saas",
      s: 85.1,
      status: "VOORLOPIG",
      lezing: "Zscaler (security_saas): cloud security / ZTNA platform. S=85,1 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "MDB",
      name: "MongoDB",
      sector: "data_platform",
      s: 84.3,
      status: "VOORLOPIG",
      lezing: "MongoDB (data_platform): document-database platform-IP. S=84,3 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "APPF",
      name: "AppFolio",
      sector: "vertical_saas",
      s: 82.2,
      status: "VOORLOPIG",
      lezing: "AppFolio (vertical_saas): property-management SaaS. S=82,2 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "WDAY",
      name: "Workday",
      sector: "hcm_erp",
      s: 81.8,
      status: "VOORLOPIG",
      lezing: "Workday (hcm_erp): HCM / financial cloud platform. S=81,8 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "SPSC",
      name: "SPS Commerce",
      sector: "vertical_saas",
      s: 81.3,
      status: "VOORLOPIG",
      lezing: "SPS Commerce (vertical_saas): retail supply-chain network SaaS. S=81,3 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "TEAM",
      name: "Atlassian",
      sector: "collab",
      s: 81.2,
      status: "VOORLOPIG",
      lezing: "Atlassian (collab): developer collaboration / Atlassian cloud. S=81,2 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "DSY",
      name: "Dassault Systèmes",
      sector: "design_plm",
      s: 80.5,
      status: "VOORLOPIG",
      lezing: "Dassault Systèmes (design_plm): industrieel 3D / PLM software. S=80,5 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "INTU",
      name: "Intuit",
      sector: "hcm_erp",
      s: 79.6,
      status: "VOORLOPIG",
      lezing: "Intuit (hcm_erp): tax / accounting platform (TurboTax/QB). S=79,6 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "NOW",
      name: "ServiceNow",
      sector: "workflow",
      s: 79.1,
      status: "VOORLOPIG",
      lezing: "ServiceNow (workflow): enterprise workflow platform. S=79,1 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "ADBE",
      name: "Adobe",
      sector: "creative",
      s: 78.2,
      status: "VOORLOPIG",
      lezing: "Adobe (creative): creative / document cloud suite. S=78,2 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "CDNS",
      name: "Cadence",
      sector: "eda",
      s: 78.2,
      status: "VOORLOPIG",
      lezing: "Cadence (eda): EDA chip-design tooling. S=78,2 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "PLTR",
      name: "Palantir",
      sector: "data_platform",
      s: 78.1,
      status: "VOORLOPIG",
      lezing: "Palantir (data_platform): data / AIP Foundry platform. S=78,1 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "ADSK",
      name: "Autodesk",
      sector: "design_plm",
      s: 78.0,
      status: "VOORLOPIG",
      lezing: "Autodesk (design_plm): design / BIM software (niet Adidas). S=78,0 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "CRM",
      name: "Salesforce",
      sector: "crm",
      s: 77.9,
      status: "VOORLOPIG",
      lezing: "Salesforce (crm): CRM cloud + AppExchange. S=77,9 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "DOCU",
      name: "Docusign",
      sector: "collab",
      s: 76.4,
      status: "VOORLOPIG",
      lezing: "Docusign (collab): e-signature / agreement cloud. S=76,4 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "AGYS",
      name: "Agilysys",
      sector: "vertical_saas",
      s: 75.8,
      status: "VOORLOPIG",
      lezing: "Agilysys (vertical_saas): hospitality PMS software. S=75,8 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "RAMP",
      name: "LiveRamp",
      sector: "data_platform",
      s: 75.8,
      status: "VOORLOPIG",
      lezing: "LiveRamp (data_platform): data collaboration / identity graph. S=75,8 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "ZM",
      name: "Zoom",
      sector: "collab",
      s: 75.5,
      status: "VOORLOPIG",
      lezing: "Zoom (collab): video communications platform. S=75,5 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "DT",
      name: "Dynatrace",
      sector: "observability",
      s: 75.1,
      status: "VOORLOPIG",
      lezing: "Dynatrace (observability): observability / APM platform. S=75,1 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "SAP",
      name: "SAP",
      sector: "hcm_erp",
      s: 74.7,
      status: "VOORLOPIG",
      lezing: "SAP (hcm_erp): ERP platform (S/4HANA). S=74,7 hergebruik europa. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "DBX",
      name: "Dropbox",
      sector: "collab",
      s: 74.6,
      status: "VOORLOPIG",
      lezing: "Dropbox (collab): content collaboration cloud. S=74,6 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "PTC",
      name: "PTC",
      sector: "design_plm",
      s: 74.4,
      status: "VOORLOPIG",
      lezing: "PTC (design_plm): industriële PLM / CAD stack. S=74,4 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "PCTY",
      name: "Paylocity",
      sector: "hcm_erp",
      s: 74.3,
      status: "VOORLOPIG",
      lezing: "Paylocity (hcm_erp): payroll / HCM SaaS. S=74,3 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "MSFT",
      name: "Microsoft",
      sector: "platform",
      s: 74.1,
      status: "VOORLOPIG",
      lezing: "Microsoft (platform): cloud + productivity software stack. S=74,1 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "OKTA",
      name: "Okta",
      sector: "security_saas",
      s: 73.7,
      status: "VOORLOPIG",
      lezing: "Okta (security_saas): identity / access platform. S=73,7 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "PAYC",
      name: "Paycom",
      sector: "hcm_erp",
      s: 73.7,
      status: "VOORLOPIG",
      lezing: "Paycom (hcm_erp): payroll / HR software platform. S=73,7 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "ACIW",
      name: "ACI Worldwide",
      sector: "payments",
      s: 71.9,
      status: "VOORLOPIG",
      lezing: "ACI Worldwide (payments): payments / merchant software. S=71,9 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "QLYS",
      name: "Qualys",
      sector: "security_saas",
      s: 71.1,
      status: "VOORLOPIG",
      lezing: "Qualys (security_saas): vulnerability management cloud. S=71,1 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "PANW",
      name: "Palo Alto Networks",
      sector: "security_saas",
      s: 70.7,
      status: "VOORLOPIG",
      lezing: "Palo Alto Networks (security_saas): network / cloud security platform. S=70,7 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "TDC",
      name: "Teradata",
      sector: "data_platform",
      s: 70.3,
      status: "VOORLOPIG",
      lezing: "Teradata (data_platform): enterprise data platform. S=70,3 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "FTNT",
      name: "Fortinet",
      sector: "security_saas",
      s: 69.7,
      status: "VOORLOPIG",
      lezing: "Fortinet (security_saas): network security / FortiGate stack. S=69,7 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "TYL",
      name: "Tyler Technologies",
      sector: "vertical_saas",
      s: 69.0,
      status: "VOORLOPIG",
      lezing: "Tyler Technologies (vertical_saas): overheidssoftware (civic cloud). S=69,0 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "FFIV",
      name: "F5",
      sector: "infra_soft",
      s: 68.2,
      status: "VOORLOPIG",
      lezing: "F5 (infra_soft): application delivery & security software. S=68,2 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "IT",
      name: "Gartner",
      sector: "research",
      s: 67.6,
      status: "VOORLOPIG",
      lezing: "Gartner (research): research / advisory IP (Gartner). S=67,6 hergebruik top100. Status VOORLOPIG. Nieuw dossier (ochtend B3/B4).",
    },
    {
      ticker: "BSY",
      name: "Bentley Systems",
      sector: "design_plm",
      s: 66.7,
      status: "VOORLOPIG",
      lezing: "Bentley Systems (design_plm): infrastructure engineering software (iTwin). S=66,7 hergebruik top100. Status VOORLOPIG. Nieuw dossier (ochtend B3/B4).",
    },
    {
      ticker: "BOX",
      name: "Box",
      sector: "collab",
      s: 65.8,
      status: "VOORLOPIG",
      lezing: "Box (collab): content cloud / collaboration. S=65,8 hergebruik top100. Status VOORLOPIG. Nieuw dossier (ochtend B3/B4).",
    },
    {
      ticker: "ROP",
      name: "Roper",
      sector: "vertical_soft",
      s: 64.8,
      status: "VOORLOPIG",
      lezing: "Roper (vertical_soft): vertical software & niche platforms. S=64,8 hergebruik top100. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "MANH",
      name: "Manhattan Associates",
      sector: "vertical_saas",
      s: 64.1,
      status: "VOORLOPIG",
      lezing: "Manhattan Associates (vertical_saas): supply-chain / WMS software. S=64,1 hergebruik top100. Status VOORLOPIG. Nieuw dossier (ochtend B3/B4).",
    },
  ],
  softwarelaag: [
    {
      ticker: "PME",
      name: "Pro Medicus",
      sector: "behoudt laag",
      s: 86.9,
      status: "VOORLOPIG",
      lezing: "Radiology imaging-software-IP behouden — SW-only, issuer houdt de laag. S=86,9 (hergebruik oceania).",
    },
    {
      ticker: "MDB",
      name: "MongoDB",
      sector: "behoudt laag",
      s: 84.3,
      status: "VOORLOPIG",
      lezing: "Document-databaseplatform — issuer houdt data-/query-IP, geen urenmodel. S=84,3 (hergebruik top100).",
    },
    {
      ticker: "TNE",
      name: "TechnologyOne",
      sector: "behoudt laag",
      s: 86.0,
      status: "VOORLOPIG",
      lezing: "Enterprise SaaS ERP-IP (SaaS+) — platform blijft bij de issuer. S=86,0 (hergebruik oceania).",
    },
    {
      ticker: "TSLA",
      name: "Tesla",
      sector: "behoudt laag",
      s: 84.6,
      status: "VOORLOPIG",
      lezing: "Archetype issuer-lens: software/FSD/data behouden over hardware heen. S=84,6 (hergebruik top100).",
    },
    {
      ticker: "XRO",
      name: "Xero",
      sector: "behoudt laag",
      s: 82.3,
      status: "VOORLOPIG",
      lezing: "Cloud accounting-IP behouden — NZ-wortels, platformlaag bij issuer. S=82,3 (hergebruik oceania).",
    },
    {
      ticker: "WTC",
      name: "WiseTech Global",
      sector: "behoudt laag",
      s: 81.9,
      status: "VOORLOPIG",
      lezing: "Logistics SaaS (CargoWise) — issuer houdt de platformlaag. S=81,9 (hergebruik oceania).",
    },
    {
      ticker: "WDAY",
      name: "Workday",
      sector: "behoudt laag",
      s: 81.8,
      status: "VOORLOPIG",
      lezing: "HCM/financieel cloudplatform — lock-in via eigen stack, niet uren. S=81,8 (hergebruik top100).",
    },
    {
      ticker: "DSY",
      name: "Dassault Systèmes",
      sector: "behoudt laag",
      s: 80.5,
      status: "VOORLOPIG",
      lezing: "Industrieel 3D/PLM-software Europa — IP blijft bij Dassault. S=80,5 (hergebruik europa).",
    },
    {
      ticker: "HEI",
      name: "HEICO",
      sector: "behoudt laag",
      s: 80.0,
      status: "VOORLOPIG",
      lezing: "Aerospace aftermarket + niche-IP — industriële software/data-adjacent keep. S=80,0 (hergebruik top100).",
    },
    {
      ticker: "INTU",
      name: "Intuit",
      sector: "behoudt laag",
      s: 79.6,
      status: "VOORLOPIG",
      lezing: "Tax/accounting-platform (TurboTax/QB) — data- en workflow-IP behouden. S=79,6 (hergebruik top100).",
    },
    {
      ticker: "NOW",
      name: "ServiceNow",
      sector: "platform (zorg)",
      s: 79.1,
      status: "VOORLOPIG",
      lezing: "Workflow-platform met sterke lock-in — keep, maar SaaS-huur-risico meewegen. S=79,1 (hergebruik top100).",
    },
    {
      ticker: "CDNS",
      name: "Cadence",
      sector: "behoudt laag",
      s: 78.2,
      status: "VOORLOPIG",
      lezing: "EDA-software — chipontwerp-IP/tooling blijft bij Cadence. S=78,2 (hergebruik top100).",
    },
    {
      ticker: "PLTR",
      name: "Palantir",
      sector: "platform (zorg)",
      s: 78.1,
      status: "VOORLOPIG",
      lezing: "Data-platform (AIP/Foundry) — keep van stack; zorg om dienstenmix. S=78,1 (hergebruik top100).",
    },
    {
      ticker: "ADSK",
      name: "Autodesk",
      sector: "behoudt laag",
      s: 78.0,
      status: "VOORLOPIG",
      lezing: "Industrieel design/BIM-software (ADSK; niet Adidas ADS) — IP bij issuer. S=78,0 (hergebruik top100).",
    },
    {
      ticker: "CRM",
      name: "Salesforce",
      sector: "platform (zorg)",
      s: 77.9,
      status: "VOORLOPIG",
      lezing: "CRM-cloudplatform — keep via AppExchange; onderscheid van pure reseller. S=77,9 (hergebruik top100).",
    },
    {
      ticker: "SAP",
      name: "SAP",
      sector: "behoudt laag",
      s: 74.7,
      status: "VOORLOPIG",
      lezing: "ERP-platform Europa (S/4HANA) — softwarelaag behouden, niet urenmodel. S=74,7 (hergebruik europa).",
    },
    {
      ticker: "WIT",
      name: "Wipro",
      sector: "huur/uren",
      s: 64.0,
      status: "VOORLOPIG",
      lezing: "Contrast: IT-services — vooral uren/outsourcing, weinig eigen productlaag. S=64,0 (hergebruik asia).",
    },
    {
      ticker: "INFY",
      name: "Infosys",
      sector: "huur/uren",
      s: 62.7,
      status: "VOORLOPIG",
      lezing: "Contrast: IT-services — uren en projecten domineren t.o.v. product-IP. S=62,7 (hergebruik asia).",
    },
    {
      ticker: "ACN",
      name: "Accenture",
      sector: "huur/uren",
      s: 59.6,
      status: "VOORLOPIG",
      lezing: "Contrast: consulting/implementatie-uren — login en mensen, niet eigen stack. S=59,6 (hergebruik top100).",
    },
    {
      ticker: "IBM",
      name: "IBM",
      sector: "huur/uren",
      s: 55.0,
      status: "VOORLOPIG",
      lezing: "Contrast: mix software+services — zwaar uren/hybrid cloud-huur in de mix. S=55,0 (hergebruik top100).",
    },
  ],
  industrieel: [
    {
      ticker: "TRN",
      name: "Trinity Industries",
      sector: "railcar_lessor",
      s: 80.6,
      status: "VOORLOPIG",
      lezing: "Railcar-lessor/manufacture. Hoge A/K; S hergebruik Top100.",
    },
    {
      ticker: "HEI",
      name: "HEICO Corporation",
      sector: "aerospace_aftermarket",
      s: 80.0,
      status: "VOORLOPIG",
      lezing: "PMA-/luchtvaart-aftermarket & ET. Cluster-anker bezit; bestaand dossier.",
    },
    {
      ticker: "GE",
      name: "GE Aerospace",
      sector: "aerospace_oem",
      s: 79.3,
      status: "VOORLOPIG",
      lezing: "Aerospace OEM + services. R wringt; dossier bestaand.",
    },
    {
      ticker: "TDG",
      name: "TransDigm",
      sector: "aerospace_aftermarket",
      s: 79.1,
      status: "VOORLOPIG",
      lezing: "Aerospace aftermarket. U/K sterk; dossier bestaand.",
    },
    {
      ticker: "ATMU",
      name: "Atmus Filtration",
      sector: "filtration_aftermarket",
      s: 74.4,
      status: "VOORLOPIG",
      lezing: "Filtratie-aftermarket. K hoog; dossier bestaand.",
    },
    {
      ticker: "LOAR",
      name: "Loar",
      sector: "aerospace_aftermarket",
      s: 74.4,
      status: "VOORLOPIG",
      lezing: "Luchtvaart-niche aftermarket. R wringt; dossier bestaand.",
    },
    {
      ticker: "GATX",
      name: "GATX Corporation",
      sector: "railcar_lessor",
      s: 72.8,
      status: "VOORLOPIG",
      lezing: "Railcar-leasevloot full-service. LESSOR_OCF_PROXY; nieuw Semaform.",
    },
    {
      ticker: "GTES",
      name: "Gates Industrial",
      sector: "industrial_components",
      s: 71.9,
      status: "VOORLOPIG",
      lezing: "Aandrijf-/vloeistof aftermarket. Dossier bestaand.",
    },
    {
      ticker: "KAI",
      name: "Kadant",
      sector: "industrial_equipment",
      s: 71.5,
      status: "VOORLOPIG",
      lezing: "Procesapparatuur & industriële aftermarket. Dossier bestaand.",
    },
    {
      ticker: "CAT",
      name: "Caterpillar",
      sector: "heavy_equipment",
      s: 67.3,
      status: "VOORLOPIG",
      lezing: "Zwaar materieel + dealer-aftermarket. Dossier bestaand.",
    },
    {
      ticker: "GEV",
      name: "GE Vernova",
      sector: "energy_equipment",
      s: 65.0,
      status: "VOORLOPIG",
      lezing: "Energy equipment + services. Dossier bestaand.",
    },
    {
      ticker: "HON",
      name: "Honeywell",
      sector: "diversified_industrials",
      s: 64.0,
      status: "VOORLOPIG",
      lezing: "Aerospace tech + automation. R wringt; dossier bestaand.",
    },
    {
      ticker: "GD",
      name: "General Dynamics",
      sector: "aerospace_defense",
      s: 62.9,
      status: "VOORLOPIG",
      lezing: "Aerospace & defense platforms. Dossier bestaand.",
    },
    {
      ticker: "WAB",
      name: "Wabtec",
      sector: "rail_oem",
      s: 61.7,
      status: "VOORLOPIG",
      lezing: "Rail equipment + freight aftermarket. Dossier bestaand.",
    },
    {
      ticker: "TT",
      name: "Trane Technologies",
      sector: "hvac_oem",
      s: 61.0,
      status: "VOORLOPIG",
      lezing: "HVAC systems + services. Dossier bestaand.",
    },
    {
      ticker: "OTIS",
      name: "Otis",
      sector: "elevator_oem",
      s: 60.8,
      status: "VOORLOPIG",
      lezing: "Elevators + service aftermarket. R laag; dossier bestaand.",
    },
    {
      ticker: "URI",
      name: "United Rentals",
      sector: "equipment_rental",
      s: 56.5,
      status: "VOORLOPIG",
      lezing: "Equipment rental-vloot / utilization. Nieuw Semaform.",
    },
    {
      ticker: "LHX",
      name: "L3Harris",
      sector: "aerospace_defense",
      s: 55.2,
      status: "VOORLOPIG",
      lezing: "Defense electronics. R wringt; dossier bestaand.",
    },
    {
      ticker: "RTX",
      name: "RTX",
      sector: "aerospace_defense",
      s: 52.4,
      status: "VOORLOPIG",
      lezing: "Aerospace engines + defense aftermarket. Dossier bestaand.",
    },
    {
      ticker: "AIR",
      name: "AAR",
      sector: "aerospace_aftermarket",
      s: null,
      status: "INCOMPLEET",
      lezing: "Top100 S=57,3 bestaat, maar companyfacts-FY stale (FY2018) — geen nieuw Semaform zonder verse 10-K-pass (prior batches skipped).",
    },
    {
      ticker: "SAND",
      name: "Sandvik",
      sector: "industrial_oem_eu",
      s: null,
      status: "INCOMPLEET",
      lezing: "EU/LEDGER — gescoord op Europa-mand (S 71,9); geen SEC-primary Semaform deze pass.",
    },
    {
      ticker: "SIE",
      name: "Siemens",
      sector: "industrial_oem_eu",
      s: null,
      status: "INCOMPLEET",
      lezing: "EU/LEDGER — gescoord op Europa-mand (S 64,3); geen SEC-primary Semaform deze pass.",
    },
    {
      ticker: "6954",
      name: "Fanuc",
      sector: "industrial_automation_jp",
      s: null,
      status: "INCOMPLEET",
      lezing: "JP/LEDGER — gescoord op Azië-mand (S 73,2); geen SEC-primary Semaform deze pass.",
    },
  ],
  landbouw: [
    {
      ticker: "ZTS",
      name: "Zoetis",
      sector: "animal_health",
      s: 77.0,
      status: "VOORLOPIG",
      lezing: "Zoetis is diergezondheid (farm-adjacent). S=77,0 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit sterk, veerkracht solide (herstel ongetest=20). Buiten de Top100-contest-universe; landbouw-mand research.",
    },
    {
      ticker: "CTVA",
      name: "Corteva",
      sector: "seeds_crop",
      s: 74.7,
      status: "VOORLOPIG",
      lezing: "Corteva is zaden / gewasbescherming (crop science). S=74,7 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit sterk, veerkracht solide (herstel ongetest=20). Buiten de Top100-contest-universe; landbouw-mand research.",
    },
    {
      ticker: "DE",
      name: "Deere & Company",
      sector: "equip",
      s: 74.2,
      status: "VOORLOPIG",
      lezing: "Deere & Company is landbouw-/zwaar materieel (OEM). S=74,2 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit sterk, veerkracht solide (herstel ongetest=20). Buiten de Top100-contest-universe; landbouw-mand research.",
    },
    {
      ticker: "LNN",
      name: "Lindsay Corporation",
      sector: "irrigation",
      s: 70.5,
      status: "VOORLOPIG",
      lezing: "Lindsay Corporation is irrigatie / water-infrastructure. S=70,5 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom solide, kas/utiliteit sterk, veerkracht solide (herstel ongetest=20). Buiten de Top100-contest-universe; landbouw-mand research.",
    },
    {
      ticker: "CF",
      name: "CF Industries",
      sector: "fertilizer",
      s: 69.0,
      status: "VOORLOPIG",
      lezing: "CF Industries is meststoffen / nutrient production. S=69,0 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit sterk, veerkracht solide (herstel ongetest=20). Buiten de Top100-contest-universe; landbouw-mand research.",
    },
    {
      ticker: "TTC",
      name: "Toro",
      sector: "irrigation",
      s: 68.4,
      status: "VOORLOPIG",
      lezing: "Toro is irrigatie / water-infrastructure. S=68,4 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit sterk, veerkracht solide (herstel ongetest=20). Buiten de Top100-contest-universe; landbouw-mand research.",
    },
    {
      ticker: "CAT",
      name: "Caterpillar",
      sector: "equip",
      s: 67.3,
      status: "VOORLOPIG",
      lezing: "Caterpillar is landbouw-/zwaar materieel (OEM). S=67,3 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit sterk, veerkracht de knip (herstel ongetest=20). Hergebruikt uit Top100/mining als equipment-adjacent.",
    },
    {
      ticker: "ALG",
      name: "Alamo Group",
      sector: "equip",
      s: 65.6,
      status: "VOORLOPIG",
      lezing: "Alamo Group is landbouw-/zwaar materieel (OEM). S=65,6 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit gemiddeld, veerkracht solide (herstel ongetest=20). Buiten de Top100-contest-universe; landbouw-mand research.",
    },
    {
      ticker: "CNH",
      name: "CNH Industrial",
      sector: "equip",
      s: 64.8,
      status: "VOORLOPIG",
      lezing: "CNH Industrial is landbouw-/zwaar materieel (OEM). S=64,8 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit gemiddeld, veerkracht solide (herstel ongetest=20). Buiten de Top100-contest-universe; landbouw-mand research.",
    },
    {
      ticker: "VMI",
      name: "Valmont Industries",
      sector: "irrigation",
      s: 63.1,
      status: "VOORLOPIG",
      lezing: "Valmont Industries is irrigatie / water-infrastructure. S=63,1 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom solide, kas/utiliteit gemiddeld, veerkracht solide (herstel ongetest=20). Buiten de Top100-contest-universe; landbouw-mand research.",
    },
    {
      ticker: "TRMB",
      name: "Trimble",
      sector: "precision_ag",
      s: 61.9,
      status: "VOORLOPIG",
      lezing: "Trimble is precision ag / software-hardware. S=61,9 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit sterk, veerkracht de knip (herstel ongetest=20). Buiten de Top100-contest-universe; landbouw-mand research.",
    },
    {
      ticker: "DAR",
      name: "Darling Ingredients",
      sector: "processor",
      s: 61.7,
      status: "VOORLOPIG",
      lezing: "Darling Ingredients is ag-processing / origination (geen food retail). S=61,7 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit gemiddeld, veerkracht solide (herstel ongetest=20). Buiten de Top100-contest-universe; landbouw-mand research.",
    },
    {
      ticker: "ELAN",
      name: "Elanco Animal Health",
      sector: "animal_health",
      s: 61.6,
      status: "VOORLOPIG",
      lezing: "Elanco Animal Health is diergezondheid (farm-adjacent). S=61,6 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit sterk, veerkracht de knip (herstel ongetest=20). Buiten de Top100-contest-universe; landbouw-mand research.",
    },
    {
      ticker: "AGCO",
      name: "AGCO",
      sector: "equip",
      s: 57.5,
      status: "VOORLOPIG",
      lezing: "AGCO is landbouw-/zwaar materieel (OEM). S=57,5 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit gemiddeld, veerkracht de knip (herstel ongetest=20). Buiten de Top100-contest-universe; landbouw-mand research.",
    },
    {
      ticker: "IPI",
      name: "Intrepid Potash",
      sector: "fertilizer",
      s: 57.5,
      status: "VOORLOPIG",
      lezing: "Intrepid Potash is meststoffen / nutrient production. S=57,5 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit zwak, veerkracht solide (herstel ongetest=20). Buiten de Top100-contest-universe; landbouw-mand research.",
    },
    {
      ticker: "NTR",
      name: "Nutrien",
      sector: "fertilizer",
      s: 57.4,
      status: "VOORLOPIG",
      lezing: "Nutrien is meststoffen / nutrient production. S=57,4 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit gemiddeld, veerkracht de knip (herstel ongetest=20). Buiten de Top100-contest-universe; landbouw-mand research.",
    },
    {
      ticker: "ADM",
      name: "Archer-Daniels-Midland",
      sector: "processor",
      s: 53.9,
      status: "VOORLOPIG",
      lezing: "Archer-Daniels-Midland is ag-processing / origination (geen food retail). S=53,9 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit gemiddeld, veerkracht de knip (herstel ongetest=20). Buiten de Top100-contest-universe; landbouw-mand research.",
    },
    {
      ticker: "FMC",
      name: "FMC",
      sector: "seeds_crop",
      s: 52.2,
      status: "VOORLOPIG",
      lezing: "FMC is zaden / gewasbescherming (crop science). S=52,2 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit zwak, veerkracht de knip (herstel ongetest=20). Buiten de Top100-contest-universe; landbouw-mand research.",
    },
    {
      ticker: "SMG",
      name: "Scotts Miracle-Gro",
      sector: "seeds_crop",
      s: 46.4,
      status: "VOORLOPIG",
      lezing: "Scotts Miracle-Gro is zaden / gewasbescherming (crop science). S=46,4 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom solide, kas/utiliteit gemiddeld, veerkracht de knip (herstel ongetest=20). Buiten de Top100-contest-universe; landbouw-mand research.",
    },
    {
      ticker: "MOS",
      name: "Mosaic",
      sector: "fertilizer",
      s: 46.0,
      status: "VOORLOPIG",
      lezing: "Mosaic is meststoffen / nutrient production. S=46,0 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit zwak, veerkracht de knip (herstel ongetest=20). Buiten de Top100-contest-universe; landbouw-mand research.",
    },
    {
      ticker: "BG",
      name: "Bunge Global",
      sector: "processor",
      s: 43.7,
      status: "VOORLOPIG",
      lezing: "Bunge Global is ag-processing / origination (geen food retail). S=43,7 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit zwak, veerkracht de knip (herstel ongetest=20). Buiten de Top100-contest-universe; landbouw-mand research.",
    },
    {
      ticker: "BAYN.DE",
      name: "Bayer",
      sector: "seeds_crop",
      s: null,
      status: "INCOMPLEET",
      lezing: "Geen SEC primary companyfacts voor crop science-segment; LSE/Xetra — ONBEREKENBAAR op mand-pass",
    },
    {
      ticker: "KUBTY",
      name: "Kubota",
      sector: "equip",
      s: null,
      status: "INCOMPLEET",
      lezing: "ADR/JP; geen bruikbare SEC companyfacts-pass deze run",
    },
    {
      ticker: "YAR.OL",
      name: "Yara International",
      sector: "fertilizer",
      s: null,
      status: "INCOMPLEET",
      lezing: "Geen SEC primary companyfacts (Oslo); niet scorebaar zonder te verzinnen",
    },
  ],
  energie: [
    {
      ticker: "CCJ",
      name: "Cameco",
      sector: "uranium",
      s: 74.0,
      status: "VOORLOPIG",
      lezing: "Cameco is uranium (nuclear fuel layer). S=74,0 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit sterk, veerkracht solide (herstel ongetest=20). Buiten de Top100-contest-universe; energie-mand research.",
    },
    {
      ticker: "EOG",
      name: "EOG Resources",
      sector: "ep",
      s: 70.4,
      status: "VOORLOPIG",
      lezing: "EOG Resources is E&P / upstream. S=70,4 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit sterk, veerkracht solide (herstel ongetest=20). Buiten de Top100-contest-universe; energie-mand research.",
    },
    {
      ticker: "SLB",
      name: "SLB",
      sector: "services",
      s: 70.3,
      status: "VOORLOPIG",
      lezing: "SLB is oilfield services. S=70,3 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom solide, kas/utiliteit sterk, veerkracht de knip (herstel ongetest=20). Buiten de Top100-contest-universe; energie-mand research.",
    },
    {
      ticker: "COP",
      name: "ConocoPhillips",
      sector: "ep",
      s: 68.7,
      status: "VOORLOPIG",
      lezing: "ConocoPhillips is E&P / upstream. S=68,7 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit sterk, veerkracht de knip (herstel ongetest=20). Buiten de Top100-contest-universe; energie-mand research.",
    },
    {
      ticker: "LNG",
      name: "Cheniere Energy",
      sector: "lng",
      s: 68.5,
      status: "VOORLOPIG",
      lezing: "Cheniere Energy is LNG liquefaction / midstream. S=68,5 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit sterk, veerkracht de knip (herstel ongetest=20). Buiten de Top100-contest-universe; energie-mand research.",
    },
    {
      ticker: "BKR",
      name: "Baker Hughes",
      sector: "services",
      s: 68.3,
      status: "VOORLOPIG",
      lezing: "Baker Hughes is oilfield services. S=68,3 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom solide, kas/utiliteit gemiddeld, veerkracht de knip (herstel ongetest=20). Buiten de Top100-contest-universe; energie-mand research.",
    },
    {
      ticker: "HAL",
      name: "Halliburton",
      sector: "services",
      s: 67.3,
      status: "VOORLOPIG",
      lezing: "Halliburton is oilfield services. S=67,3 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom solide, kas/utiliteit gemiddeld, veerkracht solide (herstel ongetest=20). Buiten de Top100-contest-universe; energie-mand research.",
    },
    {
      ticker: "CVX",
      name: "Chevron",
      sector: "integrated",
      s: 65.4,
      status: "VOORLOPIG",
      lezing: "Chevron is geintegreerde olie & gas. S=65,4 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit sterk, veerkracht de knip (herstel ongetest=20). Buiten de Top100-contest-universe; energie-mand research.",
    },
    {
      ticker: "XOM",
      name: "Exxon Mobil",
      sector: "integrated",
      s: 61.3,
      status: "VOORLOPIG",
      lezing: "Exxon Mobil is geintegreerde olie & gas. S=61,3 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit gemiddeld, veerkracht de knip (herstel ongetest=20). Buiten de Top100-contest-universe; energie-mand research.",
    },
    {
      ticker: "OXY",
      name: "Occidental Petroleum",
      sector: "ep",
      s: 60.1,
      status: "VOORLOPIG",
      lezing: "Occidental Petroleum is E&P / upstream. S=60,1 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit sterk, veerkracht de knip (herstel ongetest=20). Buiten de Top100-contest-universe; energie-mand research.",
    },
    {
      ticker: "FANG",
      name: "Diamondback Energy",
      sector: "ep",
      s: 58.3,
      status: "VOORLOPIG",
      lezing: "Diamondback Energy is E&P / upstream. S=58,3 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit sterk, veerkracht de knip (herstel ongetest=20). Buiten de Top100-contest-universe; energie-mand research.",
    },
    {
      ticker: "MPC",
      name: "Marathon Petroleum",
      sector: "refining",
      s: 48.4,
      status: "VOORLOPIG",
      lezing: "Marathon Petroleum is refining / products. S=48,4 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit zwak, veerkracht de knip (herstel ongetest=20). Buiten de Top100-contest-universe; energie-mand research.",
    },
    {
      ticker: "GEV",
      name: "GE Vernova",
      sector: "energy_equipment",
      s: 65.0,
      status: "VOORLOPIG",
      lezing: "GE Vernova is energie-equipment (footnote industrieel). S=65,0 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit gemiddeld, veerkracht de knip (herstel ongetest=20). Buiten de Top100-contest-universe; energie-mand research.",
    },
    {
      ticker: "WDS",
      name: "Woodside Energy",
      sector: "lng_ep",
      s: 58.3,
      status: "VOORLOPIG",
      lezing: "Woodside Energy is LNG/upstream (Oceania footnote). S=58,3 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit sterk, veerkracht de knip (herstel ongetest=20). Buiten de Top100-contest-universe; energie-mand research.",
    },
  ],
  azie: [
    {
      ticker: "6146",
      name: "Disco",
      sector: "japan",
      s: 75.5,
      status: "VOORLOPIG",
      lezing: "Disco (6146) — japan. S=75,5 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit sterk, veerkracht solide (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "6954",
      name: "Fanuc",
      sector: "japan",
      s: 73.2,
      status: "VOORLOPIG",
      lezing: "Fanuc (6954) — japan. S=73,2 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit sterk, veerkracht solide (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "TSM",
      name: "TSMC",
      sector: "taiwan",
      s: 72.8,
      status: "VOORLOPIG",
      lezing: "TSMC (TSM) — taiwan. S=72,8 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit sterk, veerkracht solide (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "8035",
      name: "Tokyo Electron",
      sector: "japan",
      s: 70.1,
      status: "VOORLOPIG",
      lezing: "Tokyo Electron (8035) — japan. S=70,1 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit sterk, veerkracht solide (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "6501",
      name: "Hitachi",
      sector: "japan",
      s: 69.5,
      status: "VOORLOPIG",
      lezing: "Hitachi (6501) — japan. S=69,5 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit sterk, veerkracht solide (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "6857",
      name: "Advantest",
      sector: "japan",
      s: 68.6,
      status: "VOORLOPIG",
      lezing: "Advantest (6857) — japan. S=68,6 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit sterk, veerkracht solide (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "BABA",
      name: "Alibaba",
      sector: "china/hk",
      s: 63.3,
      status: "VOORLOPIG",
      lezing: "Alibaba (BABA) — china/hk. S=63,3 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit gemiddeld, veerkracht solide (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "6301",
      name: "Komatsu",
      sector: "japan",
      s: 61.9,
      status: "VOORLOPIG",
      lezing: "Komatsu (6301) — japan. S=61,9 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit gemiddeld, veerkracht solide (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "UMC",
      name: "UMC",
      sector: "taiwan",
      s: 59.4,
      status: "VOORLOPIG",
      lezing: "UMC (UMC) — taiwan. S=59,4 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit gemiddeld, veerkracht solide (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "BIDU",
      name: "Baidu",
      sector: "china/hk",
      s: 57.1,
      status: "VOORLOPIG",
      lezing: "Baidu (BIDU) — china/hk. S=57,1 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit zwak, veerkracht solide (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "ASX",
      name: "ASE Technology",
      sector: "taiwan",
      s: 41.1,
      status: "VOORLOPIG",
      lezing: "ASE Technology (ASX) — taiwan. S=41,1 (VOORLOPIG, bedrijfsvoering-proxies): utiliteit zwak, veerkracht de knip (herstel ongetest=20). Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "6273",
      name: "SMC",
      sector: "japan",
      s: null,
      status: "INCOMPLEET",
      lezing: "SMC (6273, japan) staat in de Azië-mand, maar S is INCOMPLEET: Geen yuho-pass deze ronde; ratios ONBEREKENBAAR. Geen verzonnen ratio’s. Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "6367",
      name: "Daikin",
      sector: "japan",
      s: null,
      status: "INCOMPLEET",
      lezing: "Daikin (6367, japan) staat in de Azië-mand, maar S is INCOMPLEET: Geen yuho-pass deze ronde; ratios ONBEREKENBAAR. Geen verzonnen ratio’s. Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "6861",
      name: "Keyence",
      sector: "japan",
      s: null,
      status: "INCOMPLEET",
      lezing: "Keyence (6861, japan) staat in de Azië-mand, maar S is INCOMPLEET: Service/ARR-dollarregel niet in yuho — K-proxy ONBEREKENBAAR (geen verzonnen stickiness). Geen verzonnen ratio’s. Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "6920",
      name: "Lasertec",
      sector: "japan",
      s: null,
      status: "INCOMPLEET",
      lezing: "Lasertec (6920, japan) staat in de Azië-mand, maar S is INCOMPLEET: Geen yuho-pass deze ronde; ratios ONBEREKENBAAR. Geen verzonnen ratio’s. Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "6981",
      name: "Murata",
      sector: "japan",
      s: null,
      status: "INCOMPLEET",
      lezing: "Murata (6981, japan) staat in de Azië-mand, maar S is INCOMPLEET: Geen yuho-pass deze ronde; ratios ONBEREKENBAAR. Geen verzonnen ratio’s. Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "7735",
      name: "SCREEN Holdings",
      sector: "japan",
      s: null,
      status: "INCOMPLEET",
      lezing: "SCREEN Holdings (7735, japan) staat in de Azië-mand, maar S is INCOMPLEET: Geen yuho-pass deze ronde; ratios ONBEREKENBAAR zonder filing-extract. Geen verzonnen ratio’s. Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "9984",
      name: "SoftBank Group",
      sector: "japan",
      s: null,
      status: "INCOMPLEET",
      lezing: "SoftBank Group (9984, japan) staat in de Azië-mand, maar S is INCOMPLEET: Holding/investment vehicle — geen industriële AURA-fit zonder segment-motor; zorgvuldig: INCOMPLEET. Geen verzonnen ratio’s. Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "2454",
      name: "MediaTek",
      sector: "taiwan",
      s: null,
      status: "INCOMPLEET",
      lezing: "MediaTek (2454, taiwan) staat in de Azië-mand, maar S is INCOMPLEET: Geen SEC 20-F companyfacts; TWSE-only — ratios ONBEREKENBAAR. Geen verzonnen ratio’s. Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "000660",
      name: "SK Hynix",
      sector: "korea",
      s: null,
      status: "INCOMPLEET",
      lezing: "SK Hynix (000660, korea) staat in de Azië-mand, maar S is INCOMPLEET: CIK 2120882 companyfacts spar (ffd only); geen scoreerbare 20-F ratios. Geen verzonnen ratio’s. Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "005930",
      name: "Samsung Electronics",
      sector: "korea",
      s: null,
      status: "INCOMPLEET",
      lezing: "Samsung Electronics (005930, korea) staat in de Azië-mand, maar S is INCOMPLEET: Geen bruikbare SEC companyfacts (geen primary ADR XBRL); KRX-only — ONBEREKENBAAR. Geen verzonnen ratio’s. Aparte lijst — niet automatisch W37-universum.",
    },
    {
      ticker: "0981.HK",
      name: "SMIC",
      sector: "china/hk",
      s: null,
      status: "INCOMPLEET",
      lezing: "SMIC (0981.HK, china_hk) staat in de Azië-mand, maar S is INCOMPLEET: Geen SEC primary filer / companyfacts; HK-only — ratios ONBEREKENBAAR. Geen verzonnen ratio’s. Aparte lijst — niet automatisch W37-universum.",
    },
  ],
  oceanie: [
    {
      ticker: "PME",
      name: "Pro Medicus",
      sector: "behoudt laag",
      s: 86.9,
      status: "VOORLOPIG",
      lezing: "Radiology imaging-software-IP behouden — SW-only, issuer houdt de laag. S=86,9 (hergebruik oceania).",
    },
    {
      ticker: "TNE",
      name: "TechnologyOne",
      sector: "behoudt laag",
      s: 86.0,
      status: "VOORLOPIG",
      lezing: "Enterprise SaaS ERP-IP (SaaS+) — platform blijft bij de issuer. S=86,0 (hergebruik oceania).",
    },
    {
      ticker: "XRO",
      name: "Xero",
      sector: "behoudt laag",
      s: 82.3,
      status: "VOORLOPIG",
      lezing: "Cloud accounting-IP behouden — NZ-wortels, platformlaag bij issuer. S=82,3 (hergebruik oceania).",
    },
    {
      ticker: "WTC",
      name: "WiseTech Global",
      sector: "behoudt laag",
      s: 81.9,
      status: "VOORLOPIG",
      lezing: "Logistics SaaS (CargoWise) — issuer houdt de platformlaag. S=81,9 (hergebruik oceania).",
    },
    {
      ticker: "WDS",
      name: "Woodside Energy",
      sector: "lng_ep",
      s: 58.3,
      status: "VOORLOPIG",
      lezing: "Woodside Energy is LNG/upstream (Oceania footnote). S=58,3 (VOORLOPIG, bedrijfsvoering-proxies): operatie-eigendom hoog, kas/utiliteit sterk, veerkracht de knip (herstel ongetest=20). Buiten de Top100-contest-universe; energie-mand research.",
    },
  ],
  latam: [
    {
      ticker: "SCCO",
      name: "Southern Copper",
      sector: "koper",
      s: 69.5,
      status: "VOORLOPIG",
      lezing: "Southern Copper (miner): koperproductie (LatAm). S=69,5 hergebruik mining/WORLD. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "SQM",
      name: "SQM",
      sector: "lithium/RE",
      s: 68.1,
      status: "VOORLOPIG",
      lezing: "SQM (metal): lithium / specialty chemicals. S=68,1 hergebruik mining/WORLD. Status VOORLOPIG. Dossier aanwezig.",
    },
    {
      ticker: "VALE",
      name: "Vale",
      sector: "diversified",
      s: 58.7,
      status: "VOORLOPIG",
      lezing: "Vale (miner): ijzererts / diversified miner. S=58,7 hergebruik mining/WORLD. Status VOORLOPIG.",
    },
  ],
  coins: [
    {
      ticker: "BTC",
      name: "Bitcoin",
      sector: "protocol",
      s: null,
      status: "ONBEREKENBAAR",
      lezing: "Protocol-leeswijze. Geen AURA/S uit filings.",
    },
    {
      ticker: "ETH",
      name: "Ethereum",
      sector: "protocol",
      s: null,
      status: "ONBEREKENBAAR",
      lezing: "Protocol-leeswijze. Geen AURA/S uit filings.",
    },
    {
      ticker: "SOL",
      name: "Solana",
      sector: "protocol",
      s: null,
      status: "ONBEREKENBAAR",
      lezing: "Protocol-leeswijze. Geen AURA/S uit filings.",
    },
    {
      ticker: "AVAX",
      name: "Avalanche",
      sector: "protocol",
      s: null,
      status: "ONBEREKENBAAR",
      lezing: "Protocol-leeswijze. Geen AURA/S uit filings.",
    },
    {
      ticker: "LINK",
      name: "Chainlink",
      sector: "protocol",
      s: null,
      status: "ONBEREKENBAAR",
      lezing: "Protocol-leeswijze. Geen AURA/S uit filings.",
    },
    {
      ticker: "DOT",
      name: "Polkadot",
      sector: "protocol",
      s: null,
      status: "ONBEREKENBAAR",
      lezing: "Protocol-leeswijze. Geen AURA/S uit filings.",
    },
    {
      ticker: "ATOM",
      name: "Cosmos",
      sector: "protocol",
      s: null,
      status: "ONBEREKENBAAR",
      lezing: "Protocol-leeswijze. Geen AURA/S uit filings.",
    },
  ],
};

export const MAND_LEADS: Record<string, string> = {
  "europa": "Deze Europa-mand toont de namen uit de desk-tabel, met de S die daar al stond. S is een onderzoeksrang.",
  "mijnbouw": "Mijnbouw en royalty: streaming, goud, koper, diversified, lithium en equipment. Scores zijn hergebruikt; Atlas verzint geen nieuwe S.",
  "software": "Software en SaaS: de gehouden laag, met S uit de desk-tabel. Apart van Softwarelaag (keep versus huur).",
  "softwarelaag": "Wie de software-, data- of IP-laag houdt, en wie vooral van huur of uren leeft. Scores hergebruikt.",
  "industrieel": "Aerospace, aftermarket, railcar-lessors, rental en OEM. S komt uit de desk-tabel. Cluster bezit versus huur: HEI, GATX, URI.",
  "landbouw": "Equipment, meststoffen, zaden, precision, irrigatie, diergezondheid en processing. Alleen bestaande S; ontbrekende filings blijven INCOMPLEET.",
  "energie": "Olie-gas, uranium en LNG — de gehouden productieve laag. S uit de desk-tabel. Status voorlopig.",
  "azie": "Azië-mand: Japan, Taiwan, Korea en China/HK. Alleen desk-S; waar filings ontbreken blijft de rij INCOMPLEET.",
  "oceanie": "Oceanië-namen die al in de desk-manden staan (softwarelaag en energie). Geen verzonnen extra rijen.",
  "latam": "LatAm-namen uit de mijnbouw-mand (overlap is bedoeld). Geen verzonnen extra rijen.",
  "afrika": "Nog geen desk-tabel op dit blad voor Afrika. Atlas vult geen namen of S in.",
  "noord-amerika": "Alleen dossiers die al op dit blad staan. De volle Noord-Amerika-desk is hier nog niet overgenomen.",
  "zorg": "Zorg-namen met een dossier op dit blad. Geen extra S verzonnen.",
  "crypto": "Nog geen desk-tabel op dit blad voor crypto-equity. Atlas vult geen namen of S in.",
  "coins": "Protocolnamen zonder AURA/S uit filings. Geen S-kolom te vullen — Atlas verzint die niet.",
};

export function deskRowsForSlug(slug: string): MandRow[] {
  return MAND_ROSTERS[slug] ?? [];
}

export function previewTickers(slug: string, limit = 8): string[] {
  return deskRowsForSlug(slug)
    .filter((row) => row.s !== null)
    .slice(0, limit)
    .map((row) => row.ticker);
}
