/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MethodeRouteImport } from './routes/methode'
import { Route as ScoresRouteImport } from './routes/scores'
import { Route as WereldRouteImport } from './routes/wereld'
import { Route as ZoekRouteImport } from './routes/zoek'
import { Route as InschrijvenRouteImport } from './routes/inschrijven'
import { Route as DossiersTickerRouteImport } from './routes/dossiers.$ticker'
import { Route as NummersIndexRouteImport } from './routes/nummers.index'
import { Route as NummersSlugRouteImport } from './routes/nummers.$slug'
import { Route as WereldSlugRouteImport } from './routes/wereld.$slug'
import { Route as MandenSlugRouteImport } from './routes/manden.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodeRoute = MethodeRouteImport.update({
  id: '/methode',
  path: '/methode',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresRoute = ScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const WereldRoute = WereldRouteImport.update({
  id: '/wereld',
  path: '/wereld',
  getParentRoute: () => rootRouteImport,
} as any)
const ZoekRoute = ZoekRouteImport.update({
  id: '/zoek',
  path: '/zoek',
  getParentRoute: () => rootRouteImport,
} as any)
const InschrijvenRoute = InschrijvenRouteImport.update({
  id: '/inschrijven',
  path: '/inschrijven',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiersTickerRoute = DossiersTickerRouteImport.update({
  id: '/dossiers/$ticker',
  path: '/dossiers/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const NummersIndexRoute = NummersIndexRouteImport.update({
  id: '/nummers/',
  path: '/nummers/',
  getParentRoute: () => rootRouteImport,
} as any)
const NummersSlugRoute = NummersSlugRouteImport.update({
  id: '/nummers/$slug',
  path: '/nummers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WereldSlugRoute = WereldSlugRouteImport.update({
  id: '/wereld/$slug',
  path: '/wereld/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MandenSlugRoute = MandenSlugRouteImport.update({
  id: '/manden/$slug',
  path: '/manden/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/methode': typeof MethodeRoute
  '/scores': typeof ScoresRoute
  '/wereld': typeof WereldRoute
  '/zoek': typeof ZoekRoute
  '/inschrijven': typeof InschrijvenRoute
  '/dossiers/$ticker': typeof DossiersTickerRoute
  '/nummers/$slug': typeof NummersSlugRoute
  '/nummers/': typeof NummersIndexRoute
  '/wereld/$slug': typeof WereldSlugRoute
  '/manden/$slug': typeof MandenSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/methode': typeof MethodeRoute
  '/scores': typeof ScoresRoute
  '/wereld': typeof WereldRoute
  '/zoek': typeof ZoekRoute
  '/inschrijven': typeof InschrijvenRoute
  '/dossiers/$ticker': typeof DossiersTickerRoute
  '/nummers/$slug': typeof NummersSlugRoute
  '/nummers': typeof NummersIndexRoute
  '/wereld/$slug': typeof WereldSlugRoute
  '/manden/$slug': typeof MandenSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/methode': typeof MethodeRoute
  '/scores': typeof ScoresRoute
  '/wereld': typeof WereldRoute
  '/zoek': typeof ZoekRoute
  '/inschrijven': typeof InschrijvenRoute
  '/dossiers/$ticker': typeof DossiersTickerRoute
  '/nummers/$slug': typeof NummersSlugRoute
  '/nummers/': typeof NummersIndexRoute
  '/wereld/$slug': typeof WereldSlugRoute
  '/manden/$slug': typeof MandenSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/methode'
    | '/scores'
    | '/wereld'
    | '/zoek'
    | '/inschrijven'
    | '/dossiers/$ticker'
    | '/nummers/$slug'
    | '/nummers/'
    | '/wereld/$slug'
    | '/manden/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/methode'
    | '/scores'
    | '/wereld'
    | '/zoek'
    | '/inschrijven'
    | '/dossiers/$ticker'
    | '/nummers/$slug'
    | '/nummers'
    | '/wereld/$slug'
    | '/manden/$slug'
  id:
    | '__root__'
    | '/'
    | '/methode'
    | '/scores'
    | '/wereld'
    | '/zoek'
    | '/inschrijven'
    | '/dossiers/$ticker'
    | '/nummers/$slug'
    | '/nummers/'
    | '/wereld/$slug'
    | '/manden/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MethodeRoute: typeof MethodeRoute
  ScoresRoute: typeof ScoresRoute
  WereldRoute: typeof WereldRoute
  ZoekRoute: typeof ZoekRoute
  InschrijvenRoute: typeof InschrijvenRoute
  DossiersTickerRoute: typeof DossiersTickerRoute
  NummersSlugRoute: typeof NummersSlugRoute
  NummersIndexRoute: typeof NummersIndexRoute
  WereldSlugRoute: typeof WereldSlugRoute
  MandenSlugRoute: typeof MandenSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methode': {
      id: '/methode'
      path: '/methode'
      fullPath: '/methode'
      preLoaderRoute: typeof MethodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores': {
      id: '/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof ScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wereld': {
      id: '/wereld'
      path: '/wereld'
      fullPath: '/wereld'
      preLoaderRoute: typeof WereldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zoek': {
      id: '/zoek'
      path: '/zoek'
      fullPath: '/zoek'
      preLoaderRoute: typeof ZoekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossiers/$ticker': {
      id: '/dossiers/$ticker'
      path: '/dossiers/$ticker'
      fullPath: '/dossiers/$ticker'
      preLoaderRoute: typeof DossiersTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nummers/': {
      id: '/nummers/'
      path: '/nummers'
      fullPath: '/nummers/'
      preLoaderRoute: typeof NummersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nummers/$slug': {
      id: '/nummers/$slug'
      path: '/nummers/$slug'
      fullPath: '/nummers/$slug'
      preLoaderRoute: typeof NummersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inschrijven': {
      id: '/inschrijven'
      path: '/inschrijven'
      fullPath: '/inschrijven'
      preLoaderRoute: typeof InschrijvenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wereld/$slug': {
      id: '/wereld/$slug'
      path: '/wereld/$slug'
      fullPath: '/wereld/$slug'
      preLoaderRoute: typeof WereldSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manden/$slug': {
      id: '/manden/$slug'
      path: '/manden/$slug'
      fullPath: '/manden/$slug'
      preLoaderRoute: typeof MandenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MethodeRoute: MethodeRoute,
  ScoresRoute: ScoresRoute,
  WereldRoute: WereldRoute,
  ZoekRoute: ZoekRoute,
  InschrijvenRoute: InschrijvenRoute,
  DossiersTickerRoute: DossiersTickerRoute,
  NummersSlugRoute: NummersSlugRoute,
  NummersIndexRoute: NummersIndexRoute,
  WereldSlugRoute: WereldSlugRoute,
  MandenSlugRoute: MandenSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
